In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("C:\\Users\\User\\Desktop\\mllearning\\mlAlgorithms\\synthetic_student_performance.csv")

In [4]:
df.columns

Index(['StudentID', 'Age', 'Gender', 'Ethnicity', 'ParentalEducation',
       'StudyTimeWeekly', 'Absences', 'Tutoring', 'ParentalSupport',
       'Extracurricular', 'Sports', 'Music', 'Volunteering', 'GPA',
       'GradeClass'],
      dtype='str')

In [5]:
df.dtypes

StudentID              int64
Age                    int64
Gender                 int64
Ethnicity              int64
ParentalEducation      int64
StudyTimeWeekly        int64
Absences               int64
Tutoring               int64
ParentalSupport        int64
Extracurricular        int64
Sports                 int64
Music                  int64
Volunteering           int64
GPA                  float64
GradeClass             int64
dtype: object

In [6]:
df.isnull().sum()

StudentID            0
Age                  0
Gender               0
Ethnicity            0
ParentalEducation    0
StudyTimeWeekly      0
Absences             0
Tutoring             0
ParentalSupport      0
Extracurricular      0
Sports               0
Music                0
Volunteering         0
GPA                  0
GradeClass           0
dtype: int64

In [7]:
df["GPA"]=df["GPA"].astype("int")

In [8]:
df.dtypes

StudentID            int64
Age                  int64
Gender               int64
Ethnicity            int64
ParentalEducation    int64
StudyTimeWeekly      int64
Absences             int64
Tutoring             int64
ParentalSupport      int64
Extracurricular      int64
Sports               int64
Music                int64
Volunteering         int64
GPA                  int64
GradeClass           int64
dtype: object

In [9]:
df.head()

StudentID  Age  Gender  Ethnicity  ParentalEducation  StudyTimeWeekly  \
0       1001   17       1          1                  3               16   
1       1002   18       1          2                  0               17   
2       1003   15       1          0                  1               13   
3       1004   17       1          0                  3                6   
4       1005   17       0          1                  2                6   

   Absences  Tutoring  ParentalSupport  Extracurricular  Sports  Music  \
0        13         0                2                0       0      0   
1        28         0                2                1       1      1   
2        18         1                4                0       0      0   
3         4         0                3                1       0      0   
4        20         0                4                0       0      0   

   Volunteering  GPA  GradeClass  
0             0    3           1  
1             0    2           2  
2             1    3           0  
3             0    3           1  
4             0    3           1

In [10]:
df.drop(columns="StudentID",inplace=True)

In [11]:
df.head()

Age  Gender  Ethnicity  ParentalEducation  StudyTimeWeekly  Absences  \
0   17       1          1                  3               16        13   
1   18       1          2                  0               17        28   
2   15       1          0                  1               13        18   
3   17       1          0                  3                6         4   
4   17       0          1                  2                6        20   

   Tutoring  ParentalSupport  Extracurricular  Sports  Music  Volunteering  \
0         0                2                0       0      0             0   
1         0                2                1       1      1             0   
2         1                4                0       0      0             1   
3         0                3                1       0      0             0   
4         0                4                0       0      0             0   

   GPA  GradeClass  
0    3           1  
1    2           2  
2    3           0  
3    3           1  
4    3           1

In [14]:
X=df.iloc[:,:-1]

In [15]:
Y=df.iloc[:,-1]

In [17]:
! pip install scikit-learn
from sklearn.preprocessing import MinMaxScaler

scalar = MinMaxScaler()

scalar.fit(X)
X_scaled = scalar.transform(X)


[notice] A new release of pip is available: 23.2.1 -> 26.0
[notice] To update, run: python.exe -m pip install --upgrade pip


  Obtaining dependency information for scikit-learn from https://files.pythonhosted.org/packages/89/3c/45c352094cfa60050bcbb967b1faf246b22e93cb459f2f907b600f2ceda5/scikit_learn-1.8.0-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for scipy>=1.10.0 from https://files.pythonhosted.org/packages/52/c8/08629657ac6c0da198487ce8cd3de78e02cfde42b7f34117d56a3fe249dc/scipy-1.17.0-cp311-cp311-win_amd64.whl.metadata
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.0 kB ? eta -:--:--
     ------------------- ------------------ 30.7/61.0 kB 262.6 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/61.0 kB 327.7 kB/s eta 0:00:01
     -------------------------------------- 61.0/61.0 kB 362.2 kB/s eta 0:00:00
  Obtaining dependency information for joblib>=1.3.0 from https://files.pythonhosted.org/packages/7b/91/984aca2e

In [18]:
X_scaled

array([[0.66666667, 1.        , 0.33333333, ..., 0.        , 0.        ,
        0.5       ],
       [1.        , 1.        , 0.66666667, ..., 1.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.        , 1.        ,
        0.5       ],
       ...,
       [0.66666667, 1.        , 0.33333333, ..., 0.        , 1.        ,
        1.        ],
       [0.33333333, 0.        , 0.66666667, ..., 1.        , 0.        ,
        1.        ],
       [1.        , 1.        , 0.66666667, ..., 0.        , 1.        ,
        0.        ]], shape=(5000, 13))

In [19]:
from sklearn.model_selection import train_test_split

X_tarin,X_test,Y_train,Y_test=train_test_split(X_scaled,Y,test_size=0.2)

In [20]:
X_tarin

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.33333333, 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       ...,
       [0.33333333, 0.        , 0.        , ..., 0.        , 1.        ,
        0.5       ],
       [1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.5       ],
       [0.66666667, 1.        , 0.        , ..., 1.        , 0.        ,
        0.5       ]], shape=(4000, 13))

In [21]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()
knn.fit(X_tarin,Y_train)

KNeighborsClassifier()

In [29]:
y_pred=knn.predict(X_test)

arr=np.array(y_pred)
arr

array([0, 0, 0, 1, 0, 1, 0, 3, 0, 0, 1, 2, 2, 2, 0, 0, 0, 0, 1, 2, 0, 0,
       3, 2, 2, 3, 2, 0, 2, 3, 0, 0, 0, 0, 2, 1, 1, 2, 0, 0, 2, 0, 0, 0,
       0, 3, 1, 0, 2, 1, 2, 0, 2, 1, 3, 0, 0, 1, 0, 3, 1, 0, 0, 0, 1, 3,
       2, 0, 0, 0, 1, 0, 0, 2, 0, 0, 0, 0, 2, 0, 1, 0, 3, 1, 3, 0, 0, 0,
       0, 3, 0, 0, 0, 2, 0, 0, 2, 0, 1, 0, 2, 0, 3, 2, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 2, 0, 3, 3, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 3, 0, 1, 3,
       0, 2, 3, 0, 0, 0, 2, 0, 2, 1, 2, 3, 0, 0, 0, 0, 2, 3, 1, 3, 2, 2,
       0, 2, 0, 3, 0, 3, 0, 0, 1, 2, 0, 0, 1, 0, 2, 1, 1, 0, 1, 0, 3, 0,
       1, 2, 0, 2, 0, 0, 0, 2, 0, 1, 0, 2, 0, 0, 1, 0, 0, 2, 2, 0, 0, 0,
       1, 3, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 0,
       0, 2, 1, 0, 0, 0, 0, 2, 2, 0, 1, 0, 2, 2, 0, 0, 1, 2, 0, 2, 0, 1,
       3, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 1, 0, 1, 2, 2, 1, 2, 0, 3,
       0, 0, 1, 1, 1, 1, 2, 2, 0, 1, 0, 2, 1, 2, 1, 0, 2, 0, 3, 0, 0, 1,
       3, 0, 1, 3, 2, 1, 0, 0, 0, 1, 1, 1, 2, 1, 0,

In [30]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_pred,Y_test))

0.596
